### ISSUE TITLE
image가 안보입니다

### ISSUE THREAD

**Issue by valentine256** [dusunax/toy#32]
query 내부의 image url로 직접 접속하면 포켓몬 이미지가 보이는데 사이트 내에서는 안보입니다.
아마 next function 요청에 문제가 있는 게 아닐까 싶네요
제 파쪼옥, 거북손데스 보여주세요..
![image](https://user-images.githubusercontent.com/44939217/225318201-eaf78991-5e67-44bf-b55c-1f14a449fe0d.png)

**Comment by dusunax** [comment]
배포 환경에서 외부 도메인의 이미지를 가져올 수 없던 이슈 수정되었습니다😃
https://pokemon-mauve-two.vercel.app/

소중한 파쪼옥과 거북손데스를 확인해주세요!
추가로 소셜로그인 인증 문제는 이번주 내로 수정될 예정이에요
