### ISSUE TITLE
외부 도메인 이미지 img 태그 사용, 일부 CSS 변경, 추가 버그 수정 필요 _ 230315

### ISSUE THREAD

**Issue by dusunax** [dusunax/toy#34]
## 외부 도메인 이미지 img 태그 사용, 일부 CSS 변경, 추가 버그 수정 필요 _ 230315

- 23년 3월 15일, 저녁 10시~1시
- 외부 도메인 관련 Next Image 버그픽스
- 일부 CSS, Timer 관련 버그 수정
- #32
- #33

---

### 일부 Timer 버그 수정

---

## 외부 도메인 사용 관련, Next Image 버그 수정
  - 이미지 400에러 관련, 배포 환경과 개발 환경의 Src는 동일한 점 확인
  ![image](https://user-images.githubusercontent.com/94776135/225370039-e197745f-1153-485e-a714-6f12b5f30315.png)

### Next 이미지가 배포 환경에서 400에러가 뜨는 이유
- 🚫 Vercel로 배포한 Next.js 프로젝트에서 이미지가 400 에러가 발생하는 경우, 일반적으로 다음과 같은 이유들이 있습니다.
1. 이미지 경로 문제: 이미지 경로가 올바르지 않거나, 파일 이름이 잘못되었을 수 있습니다. 이미지 경로를 확인하고 올바른지 확인해 보세요.
2. 권한 문제: 이미지에 대한 권한이 없거나, 이미지가 private 저장소에 저장되어 있어 접근이 불가능할 수 있습니다. 이미지 파일에 대한 권한을 확인하고 필요하다면 수정하세요.
3. 최적화 및 로딩 전략: Next.js는 기본적으로 이미지 최적화 기능을 제공합니다. 이 기능을 사용하려면 **`next/image`** 컴포넌트를 사용해야 하며, 외부 이미지의 경우 **`next.config.js`** 파일에 외부 도메인을 추가해야 합니다. 설정을 확인하고 필요한 경우 수정하세요.
4. 캐싱 문제: Vercel은 캐싱 전략을 사용하여 웹 사이트의 성능을 최적화합니다. 이미지 파일의 캐싱이 올바르게 처리되지 않은 경우 문제가 발생할 수 있습니다. 캐싱 설정을 확인하고 필요하다면 수정하세요.
5. 서버 문제: 이미지가 저장된 서버에 문제가 발생한 경우, 400 에러가 발생할 수 있습니다. 서버 로그를 확인하고 문제를 해결해야 합니다.

### 관련 버그 수정을 위해 공식문서를 참고하여 next.config.js를 수정
- config에 domain 및 remotePatterns,  [https://nextjs.org/docs/api-reference/next/image](https://nextjs.org/docs/api-reference/next/image)
1. domain
    ```tsx
    iamges: {
    	domain: ["raw.githubusercontent.com"]
    }
    ```
2. remotePatterns
    ```
    images: {
      remotePatterns: [
        {
          protocol: "https",
          hostname: "raw.githubusercontent.com",
          pathname: "/PokeAPI",
        },
      ],
    },
    ```
### Next Image의 Loader와 Src
- 동일 이미지가 로컬에서는 나옴 => 배포 환경에서 나오지 않음
- 키워드 검색 : Image → Loader → unconfigured host → 이미지 최적화
- loader 로더 [https://nextjs.org/docs/api-reference/next/legacy/image#loader-configuration](https://nextjs.org/docs/api-reference/next/legacy/image#loader-configuration)
- unoptimized [https://nextjs.org/docs/messages/next-image-unconfigured-host](https://nextjs.org/docs/messages/next-image-unconfigured-host)
- [https://nextjs.org/docs/basic-features/image-optimization](https://nextjs.org/docs/basic-features/image-optimization)

### 이미지 컴포넌트의 자동 이미지 최적화 사용하지 않기
- 이미지 최적화 일단 사용하지 않고, 추후에 다시 알아보기
방법A : Image에 직접 unoptimized 추가
```tsx
{/* 포켓몬 이미지 */}
<Image
  loader={() => imgUrl}
  src={imgUrl}
  alt={"뭘까요?"}
  width={40}
  height={40}
  className={`img w-full object-contain transition-opacity ${
    imageLoaded ? "opacity-100" : "opacity-0"
  }`}
  unoptimized={true}
  onLoadingComplete={imageLoadHandler}
/>
```
방법B : config에 다음과 같이 추가
```tsx
module.exports = {
  images: {
    loader: 'imgix',
    path: 'https://example.com/myaccount/',
  },
}
```
문제점: 로컬에서는 최적화 되지 않지만, 배포 단계에서는 srcset 적용
![image](https://user-images.githubusercontent.com/94776135/225377379-b272dfdf-79fc-42c1-9b54-fa8eee8a5d71.png)

### 해결되지 않으므로 img 태그로 수정하였습니다.

📌 **최적화 관련**
**`unoptimized`** 속성을 사용하면, Next.js는 최적화된 이미지를 생성하지 않고 **`src`** 속성에 있는 원본 이미지를 사용합니다. 그러나 이 속성이 있어도 **`Image`** 컴포넌트는 여전히 **`srcset`**을 생성합니다. 이는 브라우저가 사용할 수 있는 다양한 이미지 크기와 해상도를 제공하기 위해서입니다.
만약 **`srcset`**을 사용하지 않으려면, **`Image`** 컴포넌트가 아닌, 기본 HTML의 **`<img>`** 태그를 사용해야 합니다. 다음과 같이 작성할 수 있습니다.
```
<img src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/211.png" alt="뭘까요?" width="50" height="50" loading="lazy" className="img w-full object-contain transition-opacity opacity-0" />
```
이렇게 하면 이미지 최적화를 사용하지 않고 원본 이미지를 로드하고 **`srcset`**이 생성되지 않습니다. 이 방법을 사용할 때는 주의해야 할 점이 있습니다. Next.js의 이미지 최적화를 사용하지 않으면, 이미지 로딩 성능이 저하될 수 있으며, 다양한 기기에 대한 이미지 크기 최적화가 제공되지 않습니다.

- 이미지 최적화보다 이미지가 정상적으로 나오는 것이 중요하므로 <img /> 태그로 변경하였습니다.
  - 이후 추가 학습 필요

---

## 일부 CSS 버그 수정
  - 배경색이 나오지 않던 부분 수정
    - tailwind.config.js에서 설정한 색상이 인식되지 않을 때
      - 설정한 theme이 color인지 backgroundColor인지 key 확인!
 
---

## 타이머 버그 수정
  - 타이머가 갱신될 때 1초 동안 "-1시간 -1분 -1초" 나오던 버그
  ![image](https://user-images.githubusercontent.com/94776135/225371627-078d6337-f01c-45b7-915f-d84deca099ee.png)

**Comment by valentine256** [comment]
기본적으로 외부 url로부터 가져오는 이미지를 저장하지 않고 optimization하는 방법은 없다고 알고있습니다.
next의 image optimization도 아마 static file에 대해 적용하라고 있는 기능으로 보이네요

제가 image optimization을 구현한 방법은
1. upload할 때, backend에서 image manipulation module(sharp)을 사용해서  적당히 size별 이미지 생성
2. s3에 각 사이즈별 이미지를 업로드
3. client에서 render되고있는 화면의 size를 측정
4. 측정된 size에 알맞게 image url path를 생성
5. 화면 크기에 맞는 이미지 로드

의 방법이었습니다만, bucket 사용 요금이 발생하고, 이 프로젝트에 맞게 설계하려면
1. 모튼 포켓몬의 image를 전부 저장해두는 방식 (현재 githubusercontent 사용중)
  - raw, 100, 200, 400 등으로 나누어 저장하도록 변경
2. 요청될때마다 resize 및 저장을 하여 두번째 요청부터는 저장된 이미지를 제공
정도의 방법이 있을것같네요.

그런데 포켓몬 이미지가 raw 기준으로도 100~200B정도인데 로드가 느린가요?

**Comment by amoo-sa-du** [comment]
> 
네 피드백 감사합니다!😄 용량이 상당히 작은 이미지여서 사실 이미지 로딩에 문제는 없습니다. 
다만 Next/Image로 최적화해서 이전과 차이점을 비교해보고 싶었는데, 외부 url과 optimization 관련해서 숙지가 부족했습니다.
모든 기능을 사용하는 것이 좋은 것은 아니고, 적절한 기능만 사용해서 최적화하는 것이 중요한 점을 알게 된 것 같아요.

render되는 사이즈를 측정해서 크기별 url path를 사용하는 것도 좋은 방법이네요! 
지금 DB는 firebase를 사용하고 있는데, firebase storage를 사용할 때도 여러 extension이나 Cloud Functions을 사용해서 이미지를 처리할 수 있다고 합니다.
- Cloud Function https://firebase.google.com/docs/functions?hl=ko
- 익스텐션(비용 있음) https://extensions.dev/extensions/firebase/storage-resize-images

지금까지 이미지를 api로 전송하고, 이미지 용량 최적화는 백엔드에서 처리해주는 경우만 경험해봤는데
이미지를 각 사이즈별로 직접 최적화하도록 구현해보면 재미있을 것 같아요.
현재 서비스에는 필요하지 않지만, 이미지가 필요한 프로젝트에 참고해서 진행하도록 하겠습니다~
다시 한 번 감사합니다!

**Comment by amoo-sa-du** [comment]
> 기본적으로 외부 url로부터 가져오는 이미지를 저장하지 않고 optimization하는 방법은 없다고 알고있습니다. next의 image optimization도 아마 static file에 대해 적용하라고 있는 기능으로 보이네요
> 
> 제가 image optimization을 구현한 방법은
> 
> 1. upload할 때, backend에서 image manipulation module(sharp)을 사용해서  적당히 size별 이미지 생성
> 2. s3에 각 사이즈별 이미지를 업로드
> 3. client에서 render되고있는 화면의 size를 측정
> 4. 측정된 size에 알맞게 image url path를 생성
> 5. 화면 크기에 맞는 이미지 로드
> 
> 의 방법이었습니다만, bucket 사용 요금이 발생하고, 이 프로젝트에 맞게 설계하려면
> 
> 1. 모튼 포켓몬의 image를 전부 저장해두는 방식 (현재 githubusercontent 사용중)
> 
> * raw, 100, 200, 400 등으로 나누어 저장하도록 변경
> 
> 2. 요청될때마다 resize 및 저장을 하여 두번째 요청부터는 저장된 이미지를 제공
>    정도의 방법이 있을것같네요.
> 
> 그런데 포켓몬 이미지가 raw 기준으로도 100~200B정도인데 로드가 느린가요?
> 

네 피드백 감사합니다!😄 용량이 상당히 작은 이미지여서 사실 이미지 로딩에 문제는 없습니다. 
다만 Next/Image로 최적화해서 이전과 차이점을 비교해보고 싶었는데, 외부 url과 optimization 관련해서 숙지가 부족했습니다.
모든 기능을 사용하는 것이 좋은 것은 아니고, 적절한 기능만 사용해서 최적화하는 것이 중요한 점을 알게 된 것 같아요.

render되는 사이즈를 측정해서 크기별 url path를 사용하는 것도 좋은 방법이네요! 
지금 DB는 firebase를 사용하고 있는데, firebase storage를 사용할 때도 여러 extension이나 Cloud Functions을 사용해서 이미지를 처리할 수 있다고 합니다.
- Cloud Function https://firebase.google.com/docs/functions?hl=ko
- 익스텐션(비용 있음) https://extensions.dev/extensions/firebase/storage-resize-images

지금까지 이미지를 api로 전송하고, 이미지 용량 최적화는 백엔드에서 처리해주는 경우만 경험해봤는데
이미지를 각 사이즈별로 직접 최적화하도록 구현해보면 재미있을 것 같아요.
현재 서비스에는 필요하지 않지만, 이미지가 필요한 프로젝트에 참고해서 진행하도록 하겠습니다~
다시 한 번 감사합니다!

**Comment by valentine256** [comment]
적당주의보다는 모든 기능을 다 알고, 그것을 적절하게 사용하는게 좋다고 생각합니다. 그런 면에서 매우 뛰어난 자질이 있다고 여겨지구요

**Comment by dusunax** [comment]
### 이어서 진행 😀 =>
### 불필요한 파이베이스 요청 버그 수정 (+ 버그 관련 `useTimer.tsx` 리팩토링)

=> 3월 17일에 진행하였습니다.
- #38
